# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        # cache: true
    - name: Restore dependencies
      run: |
        cd src
        cd apps
        cd MakeBookSolution
        dotnet restore 
    - name: Build
      run: |
        cd src
        cd apps
        cd MakeBookSolution
        dotnet tool restore
        dotnet r publishSingleFullWindows
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal


    - name: 'Upload nuget'
      if: startsWith(github.ref, 'refs/tags/v') # This line ensures the step runs only if a tag version is present
      uses: actions/upload-artifact@v2
      with:
        name: data_${{github.run_number}}
        path: src/apps/MakeBookSolution/release
        retention-days: 1

